service: splunk-aws-rest-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  #------- Reports ---------
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get

  updateReport:
    handler: src/updateReports.handler 
    events:
      - httpApi:
          path: /reports/{report_id} 
          method: put

  #------- Apps ---------
  getApps:
    handler: src/getApps.handler 
    events:
      - httpApi:
          path: /apps 
          method: get
  
  updateApps:
    handler: src/updateApps.handler 
    events:
      - httpApi:
          path: /apps/{app_id} 
          method: put

  #------- Categories ---------
  getCategories:
      handler: src/getCategories.handler 
      events:
        - httpApi:
            path: /categories 
            method: get

  #------- Classifications ---------
  getClassifications:
      handler: src/getClassifications.handler 
      events:
        - httpApi:
            path: /classifications
            method: get
  
  #------- Dashboards ---------
  getDashboards:
    handler: src/getDashboards.handler 
    events:
      - httpApi:
          path: /dashboard 
          method: get
  
  updateDashboards:
    handler: src/updateDashboards.handler 
    events:
      - httpApi:
          path: /dashboard/{dashboard_id} 
          method: put

  #------- Hosts ---------
  getHosts:
    handler: src/getHosts.handler 
    events:
      - httpApi:
          path: /host 
          method: get
  
  #------- Alerts ---------
  getAlerts:
    handler: src/getAlerts.handler 
    events:
      - httpApi:
          path: /alert 
          method: get
  
  updateAlerts:
    handler: src/updateAlerts.handler 
    events:
      - httpApi:
          path: /alert/{alert_id} 
          method: put

  #------- Indexes ---------
  getIndexes:
    handler: src/getIndexes.handler 
    events:
      - httpApi:
          path: /index
          method: get

  #------- Lookups ---------
  getLookups:
    handler: src/getLookups.handler 
    events:
      - httpApi:
          path: /lookup 
          method: get
  
  updateLookups:
    handler: src/updateLookups.handler 
    events:
      - httpApi:
          path: /lookup/{lookup_id} 
          method: put
  
  #------- Meta Labels ---------
  getMetaLabels:
    handler: src/getMetaLabels.handler 
    events:
      - httpApi:
          path: /meta-labels 
          method: get

  #------- Sources ---------
  getSources:
    handler: src/getSources.handler 
    events:
      - httpApi:
          path: /source 
          method: get
  
  updateSources:
    handler: src/updateSources.handler 
    events:
      - httpApi:
          path: /source/{source_id} 
          method: put

  #------- SourceTypes ---------
  getSourceTypes:
    handler: src/getSourceTypes.handler 
    events:
      - httpApi:
          path: /sourcetype
          method: get
  
  updateSourceTypes:
    handler: src/updateSourceTypes.handler 
    events:
      - httpApi:
          path: /sourcetype/{source_type_id} 
          method: put

package:
  include:
    - node_modules/**



